name: Deploy Registration System to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'registration-system/server/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r registration-system/server/requirements.txt

      - name: Create startup script
        run: |
          cd registration-system/server
          echo "#!/bin/bash" > startup.sh
          echo "cd /home/site/wwwroot" >> startup.sh
          echo "pip install -r requirements.txt" >> startup.sh
          echo "gunicorn --bind=0.0.0.0:\$PORT app:app" >> startup.sh
          chmod +x startup.sh

      - name: Create deployment package
        run: |
          cd registration-system/server
          zip -r ../../release.zip ./*

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'elysian-signup-server'
          package: release.zip
          startup-command: './startup.sh'

      - name: Configure App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --name elysian-signup-server \
              --resource-group elysian-ressource \
              --settings \
                MONGODB_URI="${{ secrets.MONGODB_URI }}" \
                JWT_SECRET="${{ secrets.JWT_SECRET }}" \
                MESSAGE_SERVICE_URL="${{ secrets.MESSAGE_SERVICE_URL }}" \
                WEBSITE_RUN_FROM_PACKAGE="1" \
                SCM_DO_BUILD_DURING_DEPLOYMENT="true" \
                PORT="8000" \
                PYTHON_ENV="production"

      - name: Configure Python
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config set \
              --name elysian-signup-server \
              --resource-group elysian-ressource \
              --linux-fx-version "PYTHON|3.9" \
              --startup-file "startup.sh"

      - name: Restart Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp restart --name elysian-signup-server --resource-group elysian-ressource
