name: Deploy Node Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: |
        cd registration-system/message-service
        npm install
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'elysian-message'
        publish-profile: ${{ secrets.AZURE_WEBAPP_MESSAGE_PUBLISH_PROFILE }}
        package: registration-system/message-service 